### ISSUE TITLE
Search within a custom post type?

### ISSUE THREAD

**Issue by enricodeleo** [WP-API/rest-filter#11]
Trying to search a custom post type returns results from all custom post types registered for rest.

I tried both `/wp-json/wp/v2/mycustomtype?search=string` and `/wp-json/wp/v2/mycustomtype?filter[s]=string`. 

Any suggestion?

**Comment by sndrgb** [comment]
Same problem, suggestions?

**Comment by enricodeleo** [comment]
Apparently some plugin like WP extended search could create some trouble with queries via rest api. So far, I found that in my case I could disable that plugin on the fly for rest requests. See my post here https://wordpress.org/support/topic/disable-it-during-rest-request/
