### ISSUE TITLE
posts_per_page filter only returns 10 items

### ISSUE THREAD

**Issue by danieldrave** [WP-API/rest-filter#12]
Hi there,

My query variables only return 10 items ?filter[orderby]=modified&filter[posts_per_page]=100

This seems to support `modified` already even though I haven't modified any code to register that as a query var. 

![screen shot 2017-02-24 at 16 37 12](https://cloud.githubusercontent.com/assets/6514915/23311910/a58872d6-faaf-11e6-8d79-e7e7b6e7da55.png)

Thanks,
Dan

**Comment by kadamwhite** [comment]
Order & posts per page should be managed using the [built-in query parameters](https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/), and do not require the use of this plugin. `filter[posts_per_page]` was deprecated in favor of `?per_page=` early last fall, prior to the merge of the API. While I have not tested to confirm that "modify" is supported out of the box, one of these should work:

- `?filter[orderby]=modified&per_page=100`
- `?orderby=modified&per_page=100`

Hope this helps!

**Comment by danieldrave** [comment]
Brilliant thank you `?filter[orderby]=modified&per_page=100` worked a treat. Thanks for the speedy reply.
