### ISSUE TITLE
Can't fetch custom post types filtered by custom meta fields.

### ISSUE THREAD

**Issue by Beleck** [WP-API/rest-filter#14]
Hi,
I have a custom post type ait-review and i want to filter them by post_id which is a custom meta fields.
I've searche a lot but all i've tried failed.

Thanks for helping :)

**Comment by jacktator** [comment]
same problem here

**Comment by JacobDB** [comment]
Me too, I thought I was doing something wrong, but I think there's just a bug.

**Comment by m10l** [comment]
@Beleck @jacktator @JacobDB 

This might help you - https://github.com/WP-API/WP-API/issues/2452#issuecomment-295786528

> After upgrade to WP 4.7 this is not working, and if you install this rest filter plugin will not work!
Just need to replace line 42 with this:
rest_query_vars rather than query_vars

**Comment by jacktator** [comment]
Applied the edit. Thanks @m10l

**Comment by fueguino84** [comment]
@jacktator your fixed version worked perfect for me. It added meta_key and meta_value filters. Thank you very much.

Now I can filter by one custom field. Can you give an example of how to use more than one filter if possible with this plugin?

**Comment by fueguino84** [comment]
It was solved adding 'meta_query' as an accepted var to the solution proposed by @jacktator.
