### ISSUE TITLE
Posts Per Page

### ISSUE THREAD

**Issue by ghost** [WP-API/rest-filter#15]
Issue with posts_per_page filter. Line in code is:
$args['post_per_page'] = $filter['posts_per_page'];
where as it should be:
$args['posts_per_page'] = $filter['posts_per_page'];
Using the current $args parameter the filter does not work correctly.

**Comment by kadamwhite** [comment]
posts_per_page is deprecated for use with [filter], we recommend to use the natively supported `?per_page=X` argument instead. This avoids situations where a query can crash your WordPress site, and also works without any plugins!
