### ISSUE TITLE
Filtering categories for custom post type

### ISSUE THREAD

**Issue by bramhechatejas** [WP-API/rest-filter#24]
Hi,

This plugin is okay for filtering tags but what if I want to filter _categories for custom post type_ e.g. **portfolio**? API call: **wp-json/wp/v2/portfolio?filter[category]=”analytics,cloud”**. Is there any way to make this work? Please let me know. 

Thanks,

**Comment by jacktator** [comment]
@bramhechatejas I believe you should do something like this 

> wp-json/wp/v2/portfolio?categories=1,2,3

. Check out [WordPress REST API Handbook list Posts](https://developer.wordpress.org/rest-api/reference/posts/#list-posts), see argument `categories`

**Comment by kadamwhite** [comment]
Filtering by slug is not recommended, ID queries are preferred. It's possible to do what you want with custom code, but it is not an intended usage of this plugin, which is provided mainly as a shim for backwards compatibility against very old versions of the REST API.
