### ISSUE TITLE
Does this work with meta_keys & meta_values?

### ISSUE THREAD

**Issue by GreenLondon** [WP-API/rest-filter#3]
I have been using this url in order to get data from my wordpress site using the rest api. Before the update to 4.7 and the deactivation of the wp rest api v2 plugin everything was working fine.

After the update the same url it worked perfectly before now fails to fetch the data even with your plugin.

http://example.com/wp-json/wp/v2/posts?filter[meta_key]=age&filter[meta_value]=10

**Comment by codeplaygoa** [comment]
`function add_query_vars_filter( $vars ){
  $vars = array_merge( $vars, array( 'meta_key', 'meta_value', 'meta_compare','meta_query','tax_query' ) );
  return $vars;
}
add_filter( 'query_vars', 'add_query_vars_filter' );


put this in your functions.php. Worked for me`

**Comment by GreenLondon** [comment]
Thanks I will give it a go

**Comment by andrewrains** [comment]
@codeplaygoa Worked! Thank you! I've been searching for 2 days for this answer.
