### ISSUE TITLE
is filter['category__in'] supported?

### ISSUE THREAD

**Issue by jfalcone** [WP-API/rest-filter#7]
I installed the plugin in my WP 4.7 system and when I use something like

/wp/v2/posts?filter['category__in']=7&per_page=100

I get every post in every category instead of just posts in category 7.

Also are there any tricks for installation or dependencies to this plugin?  

I also updated the WP-API plugin to the latest version 15

**Comment by kadamwhite** [comment]
Some filters won't be available without authentication -- but in this case, I'd use the built-in `?categories=7` query parameter of the API instead of `filter`

**Comment by jfalcone** [comment]
I'm using authentication on the call, and unfortunately since this is implemented inside of an app, changing the call requires publishing a new app and means that all of the existing apps out there are broken until either server or the app are fixed.  For me this is impacting 3 different apps.

If this plugin had worked, then I could have fixed everything all at once.  

Any idea why this isn't working?  I didn't see anything about category__in being dropped or deprecated.

**Comment by jfalcone** [comment]
Also just verified that my authentication is working by writing a post thru the API
