### ISSUE TITLE
Doesn't work with WP_REST_Request

### ISSUE THREAD

**Issue by rmtngh** [WP-API/rest-filter#8]
$request = new WP_REST_Request( 'GET', '/wp/v2/pages' );
$request->set_param( 'filter[name]', 'home' );

This will return all pages in response, instead of "home' only.

**Comment by rmccue** [comment]
The parameter's name is `filter`, and the _value_ is an object. Try `$request->set_param( 'filter', [ 'name' => 'home' ] );`
